"""Token counting and per-invocation LLM usage tracking (3-way split).

Every LLM call is recorded with three token counts:
- **cached_tokens** — SystemMessage(s); static prompt, same every call
- **input_tokens**  — HumanMessage(s) and other dynamic content
- **output_tokens**  — tokens generated by the LLM

Public API
----------
- ``count_tokens(text, model)``  — tiktoken plain-text counting (memory budgeting)
- ``record_llm_call(role, response, *, messages, model)`` — single call-site entry point
- ``reset_usage()`` / ``get_usage()`` — per-request contextvar lifecycle
- ``InvocationUsage`` — accumulator dataclass (read by agent_runner)
"""

from __future__ import annotations

import logging
from contextvars import ContextVar
from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any, Sequence

import tiktoken
from langchain_core.messages import BaseMessage, SystemMessage

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# tiktoken internals
# ---------------------------------------------------------------------------

_FALLBACK_ENCODING = "cl100k_base"
_ASSISTANT_PRIMING_TOKENS = 3
_DRIFT_WARN_RATIO = 0.30

_MODEL_OVERHEAD: dict[str, tuple[int, int]] = {
    "gpt-4o": (3, 1),
    "gpt-4o-mini": (3, 1),
    "gpt-4": (3, 1),
    "gpt-5": (3, 1),
    "gpt-3.5-turbo": (4, -1),
    "o1": (3, 1),
}


@lru_cache(maxsize=32)
def _get_encoding(model: str) -> tiktoken.Encoding:
    try:
        return tiktoken.encoding_for_model(model)
    except (KeyError, TypeError):
        logger.debug("No tiktoken encoding for %r; using %s", model, _FALLBACK_ENCODING)
        return tiktoken.get_encoding(_FALLBACK_ENCODING)


def _safe_model(model: Any) -> str:
    return model if isinstance(model, str) else "gpt-4o-mini"


def _message_overhead(model: str) -> tuple[int, int]:
    for prefix, overhead in _MODEL_OVERHEAD.items():
        if model.startswith(prefix):
            return overhead
    return (3, 1)


# ---------------------------------------------------------------------------
# Public: plain-text token counting (used by memory_format)
# ---------------------------------------------------------------------------

def count_tokens(text: str, model: str = "gpt-4o-mini") -> int:
    """Count tokens in a plain text string via tiktoken."""
    if not text:
        return 0
    return len(_get_encoding(_safe_model(model)).encode(text))


# ---------------------------------------------------------------------------
# Internal: split message list into cached vs input token counts
# ---------------------------------------------------------------------------

def _count_messages_split(
    messages: Sequence[BaseMessage | dict],
    model: str,
) -> tuple[int, int]:
    """Return (cached_tokens, input_tokens) for a chat-message list.

    ``cached_tokens`` = tokens from SystemMessage(s)
    ``input_tokens``  = tokens from everything else (HumanMessage, etc.)
    Both include per-message framing overhead.  Assistant priming tokens
    are added to the input bucket.
    """
    m = _safe_model(model)
    enc = _get_encoding(m)
    tpm, tpn = _message_overhead(m)
    cached = 0
    dynamic = 0

    for msg in messages:
        is_system = isinstance(msg, SystemMessage) or (
            isinstance(msg, dict) and msg.get("role") == "system"
        )
        if isinstance(msg, BaseMessage):
            content = msg.content or ""
        else:
            content = msg.get("content", "")

        tokens = tpm + len(enc.encode(str(content)))
        if isinstance(msg, BaseMessage):
            tokens += len(enc.encode(msg.type))
        else:
            tokens += len(enc.encode(str(msg.get("role", ""))))

        name = msg.get("name") if isinstance(msg, dict) else None
        if name:
            tokens += tpn + len(enc.encode(str(name)))

        if is_system:
            cached += tokens
        else:
            dynamic += tokens

    dynamic += _ASSISTANT_PRIMING_TOKENS
    return cached, dynamic


# ---------------------------------------------------------------------------
# Internal: extract provider-reported usage from response metadata
# ---------------------------------------------------------------------------

def _extract_provider_usage(message: BaseMessage) -> dict[str, int | None]:
    meta: dict[str, Any] = {}
    raw = getattr(message, "usage_metadata", None)
    if isinstance(raw, dict) and raw:
        meta = raw
    if not meta:
        rm = getattr(message, "response_metadata", None)
        if isinstance(rm, dict):
            for key in ("token_usage", "usage"):
                candidate = rm.get(key)
                if isinstance(candidate, dict):
                    meta = candidate
                    break

    def _pick(*keys: str) -> int | None:
        for k in keys:
            v = meta.get(k)
            if isinstance(v, (int, float)) and v >= 0:
                return int(v)
        return None

    return {
        "input_tokens": _pick("input_tokens", "prompt_tokens", "input_token_count"),
        "output_tokens": _pick("output_tokens", "completion_tokens", "output_token_count"),
    }


# ---------------------------------------------------------------------------
# Per-invocation accumulator
# ---------------------------------------------------------------------------

_invocation_usage: ContextVar["InvocationUsage | None"] = ContextVar(
    "invocation_usage", default=None,
)


@dataclass
class InvocationUsage:
    """Running totals and per-call log for one ``graph.ainvoke`` run."""

    total_cached_tokens: int = 0
    total_input_tokens: int = 0
    total_output_tokens: int = 0
    llm_calls: list[dict[str, Any]] = field(default_factory=list)


def reset_usage() -> InvocationUsage:
    """Start a fresh accumulator (call once at graph entry)."""
    u = InvocationUsage()
    _invocation_usage.set(u)
    return u


def get_usage() -> InvocationUsage | None:
    return _invocation_usage.get()


# ---------------------------------------------------------------------------
# Public entry point — one call per LLM invocation
# ---------------------------------------------------------------------------

def record_llm_call(
    role: str,
    response: BaseMessage,
    *,
    messages: Sequence[BaseMessage | dict] | None = None,
    model: str | None = None,
) -> None:
    """Record token usage for one LLM call.  No-op if no active invocation.

    Splits input into cached (SystemMessage) and input (HumanMessage) tokens.
    When the provider omits usage metadata, tiktoken estimates are used.
    """
    u = get_usage()
    if u is None:
        return

    est_cached: int | None = None
    est_input: int | None = None
    if messages is not None and model is not None:
        est_cached, est_input = _count_messages_split(messages, model)

    provider = _extract_provider_usage(response)
    provider_total_inp = provider.get("input_tokens")
    provider_out = provider.get("output_tokens")

    if est_cached is not None and est_input is not None:
        est_total_inp = est_cached + est_input
        if isinstance(provider_total_inp, int) and provider_total_inp >= 0:
            if est_total_inp > 0:
                drift = abs(provider_total_inp - est_total_inp) / est_total_inp
                if drift > _DRIFT_WARN_RATIO:
                    logger.warning(
                        "Token drift for %s: provider=%d, tiktoken=%d (%.0f%% off)",
                        role, provider_total_inp, est_total_inp, drift * 100,
                    )
                ratio = provider_total_inp / est_total_inp
                cached = int(est_cached * ratio)
                inp = provider_total_inp - cached
            else:
                cached = 0
                inp = provider_total_inp
        else:
            cached = est_cached
            inp = est_input
            logger.debug("No provider input tokens for %s; using tiktoken cached=%d input=%d", role, cached, inp)
    elif isinstance(provider_total_inp, int) and provider_total_inp >= 0:
        cached = 0
        inp = provider_total_inp
    else:
        cached = 0
        inp = 0

    out = provider_out if isinstance(provider_out, int) and provider_out >= 0 else 0

    u.total_cached_tokens += cached
    u.total_input_tokens += inp
    u.total_output_tokens += out

    logger.info(
        "%s LLM call: cached=%d, input=%d, output=%d",
        role, cached, inp, out,
    )

    entry: dict[str, Any] = {
        "role": role,
        "usage": {
            "cached_tokens": cached,
            "input_tokens": inp,
            "output_tokens": out,
        },
    }
    if model:
        entry["model"] = model
    u.llm_calls.append(entry)
